test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------


    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.language = "english"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e7afe099.name = "Upgrade from 1.4.3"
